// Day3/Assignments/Assignment3/Source/rectangle-vue/src/components/Register.vue
<script>
export default {
  data() {
    return {
      user: {
        name: "",
        address: "",
        pan: "",
      },
      paragraph: "",
    };
  },
  methods: {
    register() {
      if (
        this.user.name !== "" &&
        this.user.address !== "" &&
        this.user.pan !== ""
      )
        this.paragraph = `${this.user.name} lives in ${this.user.address} and his pan number is ${this.user.pan}.`;
    },
  },
};
</script>

<template>
  <div class="px-5 d-flex flex-column">
    <h1>Register</h1>
    <input
      type="text"
      name="name"
      id="name"
      v-model="user.name"
      placeholder="Enter your name"
      class="form-control mb-3"
    />
    <input
      type="text"
      name="address"
      id="address"
      placeholder="Enter address"
      v-model="user.address"
      class="form-control mb-3"
    />
    <input
      type="text"
      name="pan"
      id="pan"
      placeholder="Enter pan number"
      v-model="user.pan"
      class="form-control mb-3"
    />
    <button @click="register" class="btn btn-primary">Submit</button>
    <h3 class="display-6 mt-3">{{ paragraph }}</h3>
  </div>
</template>

// Day3/Assignments/Assignment1/Source/rectangle-ng/src/app/register/register.component.ts
import { Component } from '@angular/core';

interface User {
  name: string;
  address: string;
  pan: string;
}
@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent {
  user: User = {
    name: '',
    address: '',
    pan: '',
  };
  paragraph: string = '';

  register() {
    if (
      this.user.name === '' &&
      this.user.address === '' &&
      this.user.pan === ''
    ) {
      alert('Enter valid values');
      return;
    }
    this.paragraph = `${this.user.name} lives in ${this.user.address} and his PAN number is ${this.user.pan}.`;
  }
}

<div>
  <h1>Register</h1>
  <form action="javascript:void(0)" (submit)="register()">
    <div class="mb-3">
      <label for="name">Name</label>
      <input
        type="text"
        name="name"
        id="name"
        class="form-control"
        [(ngModel)]="user.name"
        placeholder="eg. Sufyan"
      />
    </div>
    <div class="mb-3">
      <label for="address">Address</label>
      <input
        type="text"
        name="address"
        id="address"
        class="form-control"
        [(ngModel)]="user.address"
        placeholder="eg. Ahmedabad"
      />
    </div>
    <div class="mb-3">
      <label for="pan">PAN Number</label>
      <input
        type="text"
        name="pan"
        id="pan"
        placeholder="eg. ABCDE1234F"
        [(ngModel)]="user.pan"
        class="form-control"
      />
    </div>
    <input type="submit" value="Submit" class="btn btn-primary" />
  </form>
  <p class="display-3">{{ paragraph }}</p>
</div>
