// Day3/Assignments/Assignment2/Source/rectangle-react/src/components/Login.js
import { useState } from "react";

const Login = () => {
  const [isLoggedIn, setLogin] = useState(false);
  const [user, setUser] = useState({ username: "", pass: "" });

  const login = (e) => {
    e.preventDefault();
    if (user.username !== "admin" && user.pass !== "admin") {
      alert("Invalid username or password");
      return;
    }
    setLogin(true);
  };

  const logout = () => {
    setUser({ username: "", pass: "" });
    setLogin(false);
  };

  return (
    <>
      {!isLoggedIn && (
        <form className="d-flex gap-1" onSubmit={login}>
          <input
            type="text"
            name="username"
            className="form-control rounded-0"
            id="username"
            value={user.username}
            onChange={(e) => {
              setUser({ ...user, username: e.target.value });
            }}
            placeholder="Username"
          />
          <input
            type="password"
            className="form-control rounded-0"
            name="password"
            id="password"
            value={user.pass}
            onChange={(e) => {
              setUser({ ...user, pass: e.target.value });
            }}
            placeholder="Password"
          />
          <input
            type="submit"
            value="Login"
            className="btn btn-primary rounded-0"
          />
        </form>
      )}
      {isLoggedIn && (
        <div className="d-flex align-items-center text-light gap-2">
          <h3 className="h3 m-0">Hello, Admin</h3>
          <button className="btn btn-danger rounded-0" onClick={logout}>
            Logout
          </button>
        </div>
      )}
    </>
  );
};

export default Login;

// Day3/Assignments/Assignment1/Source/rectangle-ng/src/app/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  username: string = '';
  key: string = '';
  isLoggedIn: boolean = false;

  login() {
    if (this.username !== 'admin' || this.key !== 'admin') {
      alert('Invalid username or password');
      return;
    }
    this.isLoggedIn = true;
  }

  logout() {
    this.username = '';
    this.key = '';
    this.isLoggedIn = false;
  }
}

<div *ngIf="!isLoggedIn; else elseBlock" class="text-light">
  <form action="javascript:void(0)" class="d-flex gap-1">
    <input
      type="text"
      name="username"
      id="username"
      class="form-control"
      placeholder="username"
      [(ngModel)]="username"
    />
    <input
      type="password"
      name="password"
      placeholder="password"
      id="password"
      class="form-control"
      [(ngModel)]="key"
    />
    <input
      type="submit"
      value="Login"
      class="btn btn-primary"
      (click)="login()"
    />
  </form>
</div>
<ng-template #elseBlock>
  <div class="d-flex gap-2 text-light align-items-center">
    <p class="lead m-0">Hello, Admin</p>
    <button class="btn btn-danger" (click)="logout()">Logout</button>
  </div>
</ng-template>
