// Day3/Assignments/Assignment1/Source/rectangle-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'rectangle-ng';
}

<nav class="navbar navbar-dark bg-dark">
  <div class="container">
    <a href="#" class="navbar-brand">Angular</a>
    <app-login></app-login>
  </div>
</nav>

<main class="container-fluid my-3">
  <div class="container">
    <div class="row">
      <aside class="col-md-7">
        <app-register></app-register>
      </aside>
      <article class="col-md-5">
        <app-rectangle></app-rectangle>
      </article>
    </div>
  </div>
</main>

// Day3/Assignments/Assignment2/Source/rectangle-react/src/App.js
import Login from "./components/Login";
import Signup from "./components/Signup";
import Rectangle from "./components/Rectangle";

function App() {
  return (
    <>
      <nav className="navbar navbar-expand-lg navbar-dark bg-black" id="nav">
        <div className="container">
          <a href="#nav" className="navbar-brand">
            <img
              src="/logo192.png"
              alt=""
              className="img-fluid"
              style={{ height: "50px" }}
            />
          </a>
          <Login />
        </div>
      </nav>

      <div className="container-fluid text-light">
        <div className="container py-5">
          <div className="row">
            <aside className="col-12 col-md-6 col-lg-4">
              <Signup />
            </aside>
            <article className="col-12 col-md-6 col-lg-8">
              <Rectangle />
            </article>
          </div>
        </div>
      </div>
    </>
  );
}

export default App;
