// Day6/Practice/Practice3/Source/parent-to-child-vue/src/App.vue
<script>
import Display from "./components/Display.vue";
export default {
  data() {
    return {
      name: "",
    };
  },
  components: {
    Display,
  },
};
</script>

<template>
  <div>
    <Display :name="name" />
    <input
      type="text"
      name="name"
      id="name"
      v-model="name"
      placeholder="Enter your name..."
    />
  </div>
</template>

// Day1/Practice/Practice2/Source/react-project/src/App.js
import Hello from "./components/Hello";
import { useState } from "react";

function App() {
  const [name, setName] = useState("");

  const handleChange = (e) => {
    setName(e.target.value);
  };

  return (
    <div>
      <Hello name={name} />
      <input
        onChange={handleChange}
        value={name}
        placeholder="Enter your name..."
      />
    </div>
  );
}

export default App;
