// Day6/Practice/Practice3/Source/parent-to-child-vue/src/App.vue
<script>
import Display from "./components/Display.vue";
export default {
  data() {
    return {
      name: "",
    };
  },
  components: {
    Display,
  },
};
</script>

<template>
  <div>
    <Display :name="name" />
    <input
      type="text"
      name="name"
      id="name"
      v-model="name"
      placeholder="Enter your name..."
    />
  </div>
</template>

// Day6/Practice/Practice2/Source/parent-to-child-react/src/App.jsx
import { useState } from "react";
import Display from "./components/Display";
function App() {
  const [name, setName] = useState("");

  return (
    <div>
      <Display name={name} />
      <input
        type="text"
        name="name"
        id="name"
        value={name}
        onChange={(e) => {
          setName(e.target.value);
        }}
        placeholder="Enter your name..."
      />
    </div>
  );
}

export default App;
