// Day3/Practice/Practice2/Source/calc-react/src/components/Calc.js
import { useState } from "react";

const Calc = (props) => {
  let [result, setResult] = useState(0);

  const calculate = () => {
    const num1 = parseInt(props.num1);
    const num2 = parseInt(props.num2);
    switch (props.operator) {
      case "+":
        setResult(num1 + num2);
        break;
      case "-":
        setResult(num1 - num2);
        break;
      case "*":
        setResult(num1 * num2);
        break;
      case "/":
        setResult(num1 / num2);
        break;
      default:
        break;
    }
  };

  return (
    <div>
      <button onClick={calculate}>Calculate</button>
      <h1>{result}</h1>
    </div>
  );
};

export default Calc;

// Day3/Practice/Practice3/Source/calc-vue/src/components/Calc.vue
<script>
export default {
  props: {
    form: {
      num1: Number,
      num2: Number,
      operator: String,
    },
  },
  methods: {
    add: (a, b) => a + b,
    div: (a, b) => a / b,
    mul: (a, b) => a * b,
    sub: (a, b) => a - b,

    calculate() {
      let num1 = this.form.num1,
        num2 = this.form.num2;

      switch (this.form.operator) {
        case "+":
          return this.add(num1, num2);
        case "-":
          return this.sub(num1, num2);
        case "/":
          return this.div(num1, num2);
        case "*":
          return this.mul(num1, num2);
        default:
          return "Invalid operator";
      }
    },
  },
};
</script>
<template>
  <h1 style="text-align: center">{{ calculate() }}</h1>
</template>
