// Day3/Assignments/Assignment2/Source/rectangle-react/src/components/Rectangle.js
import { useState } from "react";

const Rectangle = () => {
  const [rect, setRect] = useState({ length: undefined, width: undefined });
  return (
    <div className="text-lg-end">
      <h1 className="display-1 mb-3">Area of Rectangle</h1>
      <form action="javascript:void(0)" className="ms-auto w-75">
        <input
          type="number"
          name="length"
          id="length"
          placeholder="Length"
          className="form-control rounded-0 mb-3"
          value={rect.length}
          onChange={(e) => {
            setRect({ ...rect, length: parseInt(e.target.value) });
          }}
        />
        <input
          type="number"
          name="width"
          id="width"
          placeholder="Width"
          className="form-control rounded-0 mb-3"
          value={rect.width}
          onChange={(e) => {
            setRect({ ...rect, width: parseInt(e.target.value) });
          }}
        />
      </form>
      {!isNaN(rect.length) && !isNaN(rect.width) && (
        <h2 className="display-2">{rect.length * rect.width}</h2>
      )}
    </div>
  );
};

export default Rectangle;

// Day3/Assignments/Assignment1/Source/rectangle-ng/src/app/rectangle/rectangle.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-rectangle',
  templateUrl: './rectangle.component.html',
  styleUrls: ['./rectangle.component.css'],
})
export class RectangleComponent {
  length: any;
  width: any;
  area: number = 0;

  calculate = (e: SubmitEvent) => {
    e.preventDefault();
    this.area = this.length * this.width;
  };
}

<div>
  <h1>Area of Rectangle</h1>
  <form (submit)="calculate($event)" class="mb-3">
    <div class="mb-3">
      <input
        type="number"
        name="length"
        id="length"
        placeholder="Length"
        class="form-control"
        [(ngModel)]="length"
      />
    </div>
    <div class="mb-3">
      <input
        type="text"
        name="width"
        id="width"
        placeholder="Width"
        class="form-control"
        [(ngModel)]="width"
      />
    </div>
    <input type="submit" value="Calculate Area" class="btn btn-primary" />
  </form>
  <h1 class="display-1">{{ area }}</h1>
</div>
