// Day7/Practice/Practice2/Source/child-to-parent-ng/src/app/profile/profile.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styles: [],
})
export class ProfileComponent {
  @Output() nameChange = new EventEmitter<string>();

  emitEvent(name: string) {
    this.nameChange.emit(name);
  }
}

<input
  type="text"
  placeholder="Enter your name ..."
  #name
  (input)="emitEvent(name.value)"
  class="px-4 py-2 rounded-full shadow outline-none bg-slate-200 focus:shadow-xl"
/>

// Day7/Practice/Practice3/Source/child-to-parent-react/src/components/Profile.js
const Profile = (props) => {
  return (
    <input
      type="text"
      name="name"
      id="name"
      onChange={(e) => {
        props.onNameChange(e.target.value);
      }}
      placeholder="Enter your name..."
      autoComplete="off"
      className="px-4 py-2 rounded-full caret-sky-500 text-sky-500 outline-sky-500 focus:shadow-lg focus:shadow-black/50"
    />
  );
};

export default Profile;
