// Day10/Practice/Practice1/Source/profile-form-react/src/App.js
import { useState } from "react";
import { useForm } from "react-hook-form";

import Display from "./components/Display";

function App() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({ mode: "onBlur" });

  const [profiles, setProfiles] = useState([]);

  const onSubmit = (data, e) => {
    setProfiles((prev) => [...prev, data]);
    e.target.reset();
  };

  return (
    <div className="flex items-center min-h-screen bg-slate-800">
      <div className="container flex justify-center">
        <div className="p-5 space-y-8 shadow-2xl bg-slate-700 md:w-2/3 lg:w-1/2">
          <div className="">
            <h1 className="mb-5 text-2xl text-center text-white">
              Profile Form
            </h1>
            <form onSubmit={handleSubmit(onSubmit)}>
              <div className="flex flex-col gap-3">
                <input
                  type="number"
                  className="w-full px-4 py-2"
                  placeholder="Id"
                  {...register("id", { required: "Id is required." })}
                />
                {errors.id && (
                  <span className=" text-rose-500">{errors.id.message}</span>
                )}
                <input
                  type="text"
                  className="w-full px-4 py-2"
                  placeholder="Your name"
                  {...register("name", {
                    required: "Name is required.",
                    minLength: {
                      value: 3,
                      message: "Name must be at least 3 characters long.",
                    },
                  })}
                />
                {errors.name && (
                  <span className=" text-rose-500">{errors.name.message}</span>
                )}
                <input
                  type="text"
                  className="w-full px-4 py-2"
                  placeholder="Your address"
                  {...register("address", {
                    required: "Address is required.",
                  })}
                />
                {errors.address && (
                  <span className=" text-rose-500">
                    {errors.address.message}
                  </span>
                )}
                <input
                  type="submit"
                  value="Submit"
                  className="w-full px-4 py-2 text-white cursor-pointer bg-rose-600 hover:shadow"
                />
              </div>
            </form>
          </div>
          <hr className="border-slate-800" />
          <div className="text-white">
            <Display profiles={profiles} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;

// Day9/Practice/Practice1/Source/profile-form-vue/src/App.vue
<script>
import { useVuelidate } from "@vuelidate/core";
import { required, helpers, minLength } from "@vuelidate/validators";

import ErrorMessage from "./components/ErrorMessage.vue";
import Display from "./components/Display.vue";

export default {
  components: {
    ErrorMessage,
    Display,
  },
  data() {
    return {
      v$: useVuelidate(),
      id: null,
      name: "",
      address: "",
      profiles: [],
    };
  },
  validations() {
    return {
      id: { required: helpers.withMessage("Id is required", required) },
      name: {
        required: helpers.withMessage("Name is required", required),
        minLength: helpers.withMessage(
          "Name must be at least 3 characters long",
          minLength(3)
        ),
      },
      address: {
        required: helpers.withMessage("Address is required.", required),
      },
    };
  },
  methods: {
    submit(e) {
      e.preventDefault();

      if (!this.v$.$validate()) return;

      this.profiles.push({
        id: this.id,
        name: this.name,
        address: this.address,
      });
    },
  },
};
</script>
<template>
  <form @submit="submit">
    <input
      type="number"
      name="id"
      id="id"
      v-model="id"
      @blur="v$.id.$touch"
      placeholder="id"
    />
    <ErrorMessage :errors="v$.id.$errors" />
    <input
      type="text"
      name="name"
      id="name"
      placeholder="name"
      v-model="name"
      @blur="v$.name.$touch"
    />
    <ErrorMessage :errors="v$.name.$errors" />
    <input
      type="text"
      name="address"
      id="address"
      placeholder="address"
      v-model="address"
      @blur="v$.address.$touch"
    />
    <ErrorMessage :errors="v$.address.$errors" />
    <button type="submit">Submit</button>
  </form>
  <Display :profiles="profiles" />
</template>
