// Day9/Assignments/Assignment1/Source/admission-form-vue/src/App.vue
<script>
import AdmissionForm from "./components/AdmissionForm.vue";

export default {
  components: {
    AdmissionForm,
  },
};
</script>
<template>
  <div class="flex justify-center min-h-screen bg-slate-800">
    <div class="py-10">
      <div class="container">
        <div class="p-12 text-white shadow-xl bg-slate-700">
          <h1 class="mb-5 text-3xl">Admission Form</h1>
          <AdmissionForm />
        </div>
      </div>
    </div>
  </div>
</template>

// Day7/Assignments/Assignment2/Source/react/src/App.jsx
import PostList from "./components/PostList";

function App() {
  return (
    <div className="mb-10">
      <div className="flex items-center justify-center h-16">
        <div className="container">
          <h1 className="m-0 text-3xl text-center text-primary">Posts</h1>
        </div>
      </div>
      <div className="container mt-5">
        <PostList />
      </div>
    </div>
  );
}

export default App;
