// Day7/Assignments/Assignment3/Source/post-vue/src/App.vue
<script>
import PostList from "./components/PostList.vue";
export default {
  components: {
    PostList,
  },
};
</script>

<template>
  <div class="mb-10">
    <div class="flex items-center justify-center h-16">
      <div class="container">
        <h1 class="m-0 text-3xl text-center text-primary">Posts</h1>
      </div>
    </div>
    <div class="container mt-5">
      <PostList />
    </div>
  </div>
</template>

// Day7/Assignments/Assignment2/Source/react/src/App.jsx
import PostList from "./components/PostList";

function App() {
  return (
    <div className="mb-10">
      <div className="flex items-center justify-center h-16">
        <div className="container">
          <h1 className="m-0 text-3xl text-center text-primary">Posts</h1>
        </div>
      </div>
      <div className="container mt-5">
        <PostList />
      </div>
    </div>
  );
}

export default App;
