// Day9/Assignments/Assignment1/Source/admission-form-vue/src/App.vue
<script>
import AdmissionForm from "./components/AdmissionForm.vue";

export default {
  components: {
    AdmissionForm,
  },
};
</script>
<template>
  <div class="flex justify-center min-h-screen bg-slate-800">
    <div class="py-10">
      <div class="container">
        <div class="p-12 text-white shadow-xl bg-slate-700">
          <h1 class="mb-5 text-3xl">Admission Form</h1>
          <AdmissionForm />
        </div>
      </div>
    </div>
  </div>
</template>

// Day6/Assignments/Assignment1/Source/products-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = 'products-ng';
}

<div class="flex items-center justify-center min-h-screen bg-slate-200">
  <div class="container pt-10">
    <app-products-list></app-products-list>
  </div>
</div>
