// Day5/Practice/Practice2/Source/greater-react/src/components/Greater.js
import { useState } from "react";

import "./Greater.css";

const Greater = () => {
  const [form, setForm] = useState({ num1: undefined, num2: undefined });
  return (
    <div>
      <div>
        <form action="">
          <input
            type="number"
            name="num1"
            id="num1"
            onChange={(e) => {
              setForm({ ...form, num1: parseInt(e.target.value) });
            }}
            value={form.num1}
          />
          <input
            type="number"
            name="num2"
            id="num2"
            onChange={(e) => {
              setForm({ ...form, num2: parseInt(e.target.value) });
            }}
            value={form.num2}
          />
        </form>
      </div>
      {!isNaN(form.num1) && !isNaN(form.num2) && (
        <h1>
          {form.num1 > form.num2 ? (
            form.num1
          ) : (
            <>{form.num2 > form.num1 ? form.num2 : "Equal"}</>
          )}
        </h1>
      )}
    </div>
  );
};

export default Greater;

// Day4/Practice/Practice2/Source/greater-ng/src/app/greater/greater.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-greater',
  templateUrl: './greater.component.html',
  styleUrls: ['./greater.component.css'],
})
export class GreaterComponent {
  num1: any;
  num2: any;
}

<h1>Find Greater Number</h1>
<form action="">
  <input
    type="number"
    name="num1"
    id="num1"
    placeholder="Enter a number"
    [(ngModel)]="num1"
  />
  <input
    type="number"
    name="num2"
    id="num2"
    placeholder="Enter another number"
    [(ngModel)]="num2"
  />
</form>

<app-result [num1]="num1" [num2]="num2"></app-result>
