// Day7/Practice/Practice3/Source/child-to-parent-react/src/App.js
import { useState } from "react";
import Profile from "./components/Profile";

const App = () => {
  const [Name, setName] = useState("");

  const handleNameChange = (value) => {
    setName(value);
  };
  return (
    <div className="flex items-center justify-center min-h-screen text-white bg-gradient-to-b from-sky-600 via-sky-500 to-sky-400">
      <div className="text-center">
        {Name && <h1 className="mb-3 text-2xl">Hello, {Name}.</h1>}
        <Profile onNameChange={handleNameChange} />
      </div>
    </div>
  );
};

export default App;

// Day7/Practice/Practice1/Source/child-to-parent-vue/src/App.vue
<script>
import Child from "./components/Child.vue";
export default {
  components: {
    Child,
  },
  data() {
    return {
      name: "",
    };
  },
  methods: {
    handleInput(name) {
      this.name = name;
    },
  },
};
</script>

<template>
  <div class="flex min-h-screen justify-center items-center bg-slate-200">
    <div>
      <h1 class="text-3xl font-bold text-center mb-3" v-if="name">
        Hello, {{ name }}.
      </h1>
      <Child @input="handleInput"></Child>
    </div>
  </div>
</template>
