// Day3/Assignments/Assignment2/Source/rectangle-react/src/components/Login.js
import { useState } from "react";

const Login = () => {
  const [isLoggedIn, setLogin] = useState(false);
  const [user, setUser] = useState({ username: "", pass: "" });

  const login = (e) => {
    e.preventDefault();
    if (user.username !== "admin" && user.pass !== "admin") {
      alert("Invalid username or password");
      return;
    }
    setLogin(true);
  };

  const logout = () => {
    setUser({ username: "", pass: "" });
    setLogin(false);
  };

  return (
    <>
      {!isLoggedIn && (
        <form className="d-flex gap-1" onSubmit={login}>
          <input
            type="text"
            name="username"
            className="form-control rounded-0"
            id="username"
            value={user.username}
            onChange={(e) => {
              setUser({ ...user, username: e.target.value });
            }}
            placeholder="Username"
          />
          <input
            type="password"
            className="form-control rounded-0"
            name="password"
            id="password"
            value={user.pass}
            onChange={(e) => {
              setUser({ ...user, pass: e.target.value });
            }}
            placeholder="Password"
          />
          <input
            type="submit"
            value="Login"
            className="btn btn-primary rounded-0"
          />
        </form>
      )}
      {isLoggedIn && (
        <div className="d-flex align-items-center text-light gap-2">
          <h3 className="h3 m-0">Hello, Admin</h3>
          <button className="btn btn-danger rounded-0" onClick={logout}>
            Logout
          </button>
        </div>
      )}
    </>
  );
};

export default Login;

// Day3/Assignments/Assignment3/Source/rectangle-vue/src/components/Login.vue
<script>
export default {
  data() {
    return {
      username: "",
      key: "",
      isLoggedIn: false,
    };
  },
  methods: {
    login() {
      if (this.username !== "admin" && this.key !== "admin") {
        alert("Invalid username or password");
        return;
      }
      this.isLoggedIn = true;
    },
    logout() {
      this.username = "";
      this.key = "";
      this.isLoggedIn = false;
    },
  },
};
</script>

<template>
  <div v-if="!isLoggedIn" class="text-center">
    <h1>Login</h1>
    <input
      type="text"
      name="username"
      id="username"
      v-model="username"
      placeholder="Enter username"
      class="form-control mb-3"
    />
    <input
      type="password"
      name="password"
      id="password"
      v-model="key"
      placeholder="Enter password"
      class="form-control mb-3"
    />
    <input type="submit" value="Login" @click="login" class="btn btn-primary" />
  </div>
  <div v-else class="text-end">
    <h1>Hello, {{ username }}</h1>
    <button @click="logout" class="btn btn-danger">Logout</button>
  </div>
</template>
