// Day3/Practice/Practice3/Source/calc-vue/src/App.vue
<script>
import Calc from "./components/Calc.vue";

export default {
  components: {
    Calc,
  },
  data() {
    return {
      form: {
        num1: 0,
        num2: 0,
        operator: "+",
      },
    };
  },
};
</script>

<template>
  <main>
    <div>
      <div class="input">
        <label for="num1">Number 1:</label>
        <input type="number" name="num1" id="num1" v-model="form.num1" />
      </div>
      <div class="input">
        <label for="num2">Number 2:</label>
        <input type="number" name="num2" id="num2" v-model="form.num2" />
      </div>
      <div class="input">
        <label for="operator">Operator:</label>
        <select name="operator" id="operator" v-model="form.operator">
          <option value="+">+</option>
          <option value="-">-</option>
          <option value="*">*</option>
          <option value="/">/</option>
        </select>
      </div>
    </div>
    <Calc :form="form"></Calc>
  </main>
</template>

<style>
main {
  display: flex;
  height: 100vh;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.input {
  display: flex;
  flex-direction: column;
  gap: 0.3rem;
  margin-bottom: 1rem;
}

input::-webkit-inner-spin-button {
  display: none;
}
input,
select {
  flex: 1;
  padding: 0.3rem;
}
</style>

// Day3/Practice/Practice2/Source/calc-react/src/App.js
import { useState } from "react";
import Calc from "./components/Calc";

function App() {
  const [num1, setNum1] = useState(0);
  const [num2, setNum2] = useState(0);
  const [operator, setOperator] = useState("+");
  return (
    <main>
      <div>
        <div>
          <label htmlFor="num1">Number 1</label>
          <input
            type="number"
            name="num1"
            id="num1"
            value={num1}
            onChange={(e) => {
              setNum1(e.target.value);
            }}
          />
        </div>
        <div>
          <label htmlFor="num1">Number 2</label>
          <input
            type="number"
            name="num2"
            id="num2"
            value={num2}
            onChange={(e) => {
              setNum2(e.target.value);
            }}
          />
        </div>
        <div>
          <select
            name="operator"
            id="operator"
            value={operator}
            onChange={(e) => {
              setOperator(e.target.value);
            }}
          >
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
          </select>
        </div>
      </div>
      <Calc num1={num1} num2={num2} operator={operator}></Calc>
    </main>
  );
}

export default App;
