// Day2/Practice/Practice1/Source/atoz/src/app/alphabets/alphabets.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-alphabets',
  templateUrl: './alphabets.component.html',
})
export class AlphabetsComponent {
  alphabets: string[] = [];

  constructor() {
    for (let i = 65; i < 91; i++) {
      this.alphabets.push(String.fromCharCode(i));
    }
  }
}

<style>
  .wrapper {
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
  }

  .alphabet {
    font-size: 2rem;
    background-color: rgb(63, 75, 185);
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100px;
    width: 100px;
    color: white;
    cursor: pointer;
    transition: all 0.5s;
    border-radius: 24px;
  }

  .alphabet:hover {
    background-color: rgb(27, 35, 104);
    border-radius: 0%;
    font-size: 4rem;
  }
</style>

<div class="wrapper">
  <div *ngFor="let alphabet of alphabets" class="alphabet">
    {{ alphabet }}
  </div>
</div>

// Day2/Practice/Practice2/Source/atoz-vue/src/components/Alphabets.vue
<script>
export default {
  computed: {
    alphabets() {
      const alphabets = [];
      for (let i = 65; i < 91; i++) {
        alphabets.push(String.fromCharCode(i));
      }
      return alphabets;
    },
  },
};
</script>

<template>
  <div>
    <ul>
      <li v-for="alphabet of alphabets">
        {{ alphabet }}
      </li>
    </ul>
  </div>
</template>

<style scoped>
div {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
}
ul {
  list-style-type: none;
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  font-size: 64px;
  width: 720px;
}
ul > li {
  background-color: antiquewhite;
  padding-left: 12px;
  height: 100px;
  width: 100px;
}
</style>
