// Day6/Practice/Practice2/Source/parent-to-child-react/src/App.jsx
import { useState } from "react";
import Display from "./components/Display";
function App() {
  const [name, setName] = useState("");

  return (
    <div>
      <Display name={name} />
      <input
        type="text"
        name="name"
        id="name"
        value={name}
        onChange={(e) => {
          setName(e.target.value);
        }}
        placeholder="Enter your name..."
      />
    </div>
  );
}

export default App;

// Day6/Practice/Practice1/Source/parent-to-child-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = 'parent-to-child-ng';
  name: string = '';
}

<div>
  <app-display [name]="name"></app-display>
  <input
    type="text"
    name="name"
    id="name"
    [(ngModel)]="name"
    placeholder="Write your name here."
  />
</div>
